// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Database.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Notifications")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool?>("IsEmailSend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_send");

                    b.Property<bool?>("IsWebSend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_web_send");

                    b.HasKey("UserId")
                        .HasName("user_id");

                    b.ToTable("UserNotificationSettings", "Notifications", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("user_notification_settings_user_id");
                        });
                });

            modelBuilder.Entity("NotificationService.Domain.UserNotificationSettings", b =>
                {
                    b.OwnsOne("NotificationService.Core.VO.TelegramSettings", "TelegramSettings", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationSettingsUserId")
                                .HasColumnType("uuid");

                            b1.Property<long>("ChatId")
                                .HasColumnType("bigint")
                                .HasColumnName("chat_id");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("user_id");

                            b1.HasKey("UserNotificationSettingsUserId");

                            b1.ToTable("UserNotificationSettings", "Notifications");

                            b1.ToJson("telegram_settings");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationSettingsUserId")
                                .HasConstraintName("fk_user_notification_settings_user_notification_settings_user_id");
                        });

                    b.Navigation("TelegramSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
