// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHome.VolunteerRequests.Infrastructure.Database.Read.DBContext;

#nullable disable

namespace PetHome.VolunteerRequests.Infrastructure.Migrations.Read
{
    [DbContext(typeof(VolunteerRequestReadDbContext))]
    [Migration("20250226161711_VolunteerRequests_Read_InitMigrations")]
    partial class VolunteerRequests_Read_InitMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VolunteerRequests")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHome.VolunteerRequests.Application.Database.Dto.VolunteerRequestDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DiscussionId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.Property<string>("RejectedComment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rejected_comment");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("request_status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VolunteerInfo")
                        .HasColumnType("text")
                        .HasColumnName("volunteer_info");

                    b.HasKey("Id")
                        .HasName("pk_volunteer_requests");

                    b.ToTable("VolunteerRequests", "VolunteerRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
